### ISSUE TITLE
node-gyp error

### ISSUE THREAD

**Issue by James1x0** [dkiyatkin/node-office#10]
```
> node-expat@2.0.0 install /var/www/vhosts/***************/node_modules/office/node_modules/xml2json/node_modules/node-expat
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/g                                                 yp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
AttributeError: 'module' object has no attribute 'script_main'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_mo                                                 dules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:                                                 17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_pr                                                 ocess.js:789:12)
gyp ERR! System Linux 2.6.32-042stab081.5
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modul                                                 es/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/vhosts***************node_modules                                                 /office/node_modules/xml2json/node_modules/node-expat
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
npm ERR! node-expat@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.0.0 install script.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-042stab081.5
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "instal                                                 l" "office"
npm ERR! cwd /var/www/vhosts/***************
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/vhosts/****************/npm-debug.lo                                                 g
npm ERR! not ok code 0
```

**Comment by q2dg** [comment]
Well, I have a similar error, but with Node v0.11.14 (and Fedora 20 64 bits)

**\* A LOT OF ERROR MESSAGES LIKE THESE ***
   ^
../node-expat.cc: In static member function ‘static v8::Handlev8::Value Parser::Resume(const int&)’:
../node-expat.cc:237:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
../node-expat.cc: In static member function ‘static v8::Handlev8::Value Parser::Stop(const int&)’:
../node-expat.cc:220:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
../node-expat.cc: In static member function ‘static v8::Handlev8::Value Parser::GetError(const int&)’:
../node-expat.cc:208:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
../node-expat.cc: In static member function ‘static v8::Handlev8::Value Parser::SetEncoding(const int&)’:
../node-expat.cc:189:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
../node-expat.cc: In static member function ‘static v8::Handlev8::Value Parser::Parse(const int&)’:
../node-expat.cc:139:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
make: **\* [Release/obj.target/node_expat/node-expat.o] Error 1
make: Leaving directory `/home/user/node_modules/office/node_modules/xml2json/node_modules/node-expat/build'
gyp ERR! build error 
gyp ERR! stack Error:`make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Linux 3.16.7-200.fc20.x86_64
gyp ERR! command "node" "/home/user/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/node_modules/office/node_modules/xml2json/node_modules/node-expat
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

npm ERR! Linux 3.16.7-200.fc20.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "office"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! node-expat@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1

**Comment by James1x0** [comment]
@q2dg https://github.com/dbashford/textract is a lot better anyways.
